server:
  port: 8080
 
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/oauth2?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: oauth
    password: oauth
    driver-class-name: com.mysql.jdbc.Driver
  redis:
    host: 172.24.8.123
    database: 0
 
security:
  oauth2:
    resource:
      filter-order: 3
